# Generated by Django 4.2.6 on 2023-10-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('building_num', models.PositiveSmallIntegerField(verbose_name='Номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('launch_date', models.DateField(verbose_name='Дата выхода продукта на рынок')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('level', models.CharField(choices=[(0, 0), (1, 1), (2, 2)], max_length=50)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.contact', verbose_name='Контакт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.product', verbose_name='Продукт')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.networkelement', verbose_name='Поставщик')),
            ],
        ),
    ]
