# Generated by Django 4.2.6 on 2023-11-04 13:39

from django.db import migrations, models
import django.db.models.deletion
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_networkelement_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkelement',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.networkelement', validators=[network.models.validate_provider_not_self], verbose_name='Поставщик'),
        ),
    ]
