# Generated by Django 4.2.6 on 2023-11-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_networkelement_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkelement',
            name='product',
        ),
        migrations.AddField(
            model_name='networkelement',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='network.product', verbose_name='Продукты'),
        ),
    ]
