# Generated by Django 4.2.6 on 2023-11-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_networkelement_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkelement',
            name='level',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=50, null=True),
        ),
    ]
